#!/usr/bin/env bash
bucket_name="YOUR BUCKET NAME"
basePath=/home/ubuntu/videos
cd $basePath

inotifywait -m -q -e close_write --format %f . | while IFS= read -r file; do
   year=`date +%Y`
   month=`date +%m`
   day=`date +%d`
   aws s3 mv "$basePath/$file" s3://${bucket_name}/cam01/$year/$month/$day/$file
done
